### PR TITLE
Fix tests

### LINKED ISSUE #5: failing unit tests - help wanted?
> NOTE: (2013-07-10) In the last few months I've been struggling with a few tests crashing for some reason I cannot isolate. I've pushed the latest version of the source code, and if anyone can help solve those issues it would greatly help this project.

Still interested in some help on this?

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes #5 

image

image

See https://ci.appveyor.com/project/304NotModified/nsoup/builds/22303568

If you need help in setting up appveyor, I would be happy to help -  I could do it also if you give me the needed permissions :)

### CODE REVIEW

**Comment by 304NotModified** [comment]
polite bump @GeReV

**Comment by GeReV** [comment]
Oh, wow, @304NotModified, I completely ignored this repo for quite a while. Sorry about that.

Would you like to be added as a contributor to this project?

**Comment by 304NotModified** [comment]
:+1:

**Comment by GeReV** [comment]
Awesome. Feel free to make any changes you'd like, and thanks for picking this up!
I hope I can join in again at some later time.

**Pull request merged**
